### ISSUE TITLE
Remove need for --output_groups=+mypy

### ISSUE THREAD

**Issue by thundergolfer** [bazel-contrib/bazel-mypy-integration#18]
Hopefully Aspects are allowed to return `DefaultInfo`, and I can do away with having the `mypy` output group which must be requested explicitly with `--output_groups=+mypy`.

**Comment by thundergolfer** [comment]
It appears you still can't use `DefaultInfo` to avoid needing `--output_groups=+mypy` on the command line. 

I think I should make an issue about this on `bazelbuild/bazel`.

**Comment by adzenith** [comment]
This is unfortunately still not possible in Bazel. I'm going to close this ticket for now, and if this becomes an option we can explore it then.
