### ISSUE TITLE
Customize where the .py.data.json and .py.meta.json files are generated

### ISSUE THREAD

**Issue by ashwin153** [bazel-contrib/bazel-mypy-integration#31]
Is there a way to configure the output directory? Currently, they get generated next to the sources but I would prefer if they got generated in a hidden directory so that I don't have to see them when I'm navigating through my codebase.

**Comment by adzenith** [comment]
I'm trying to clean up old issues and I'm going to close this because it's kind of a duplicate of #48.
Files shouldn't be written to the repo, certainly. Are you using sandboxed execution?
