### ISSUE TITLE
Allow passing a custom mypy executable

### ISSUE THREAD

**Issue by person142** [bazel-contrib/bazel-mypy-integration#34]
This is one approach to https://github.com/thundergolfer/bazel-mypy-integration/issues/19.

We have a custom `py_binary` wrapping mypy that bundles some plugins. Is the project open to allowing users to pass their own mypy? The simple way would be making `_mypy_cli` public:

https://github.com/thundergolfer/bazel-mypy-integration/blob/master/mypy.bzl#L23

The more proper way would probably be making a mypy toolchain.

Willing to PR this if it's acceptable.

**Comment by thundergolfer** [comment]
I thinking being able to pass the MyPy binary is entirely reasonable. #30 seems like something worth looking at too.

**Comment by adzenith** [comment]
This feature just landed in https://github.com/bazel-contrib/bazel-mypy-integration/pull/98
