### ISSUE TITLE
Learn from `dropbox/dbx_build_tools`

### ISSUE THREAD

**Issue by thundergolfer** [bazel-contrib/bazel-mypy-integration#5]
### Description 

Finally found some open-sourced MyPy integration code from Dropbox: https://github.com/dropbox/dbx_build_tools/blob/master/build_tools/py/mypy.bzl

They seem to do things in a pretty Dropbox-specific way, but I'm sure there's plenty to be learned from their code.

**Comment by alexeagle** [comment]
@dzbarsky has some experience with dbx_build_tools and can help us figure out which design elements and features to borrow.

**Comment by thundergolfer** [comment]
I'll close this. I originally opened these tickets as personal TODO tracking.
