### ISSUE TITLE
Error with rules_python-0.13.0

### ISSUE THREAD

**Issue by ph03** [bazel-contrib/bazel-mypy-integration#69]
Upgrading to `rules_python-0.13.0` results in

```
external/mypy_integration/mypy/BUILD:3:10: no such package '@mypy_integration_pip_deps_mypy//': The repository '@mypy_integration_pip_deps_mypy' could not be resolved: Repository '@mypy_integration_pip_deps_mypy' is not defined and referenced by '@mypy_integration//mypy:mypy'
````

which is likely due to https://github.com/bazelbuild/rules_python/pull/807 which suggest to change to `pip_parse` instead of `pip_install`.

**Comment by cristifalcas** [comment]
you can add this after loading the repo:
```py
pip_parse(
    name = "mypy_integration_pip_deps",
    python_interpreter_target = python_interpreter,
    requirements_lock = "//path/to/local/lock_file/mypy:requirements3.lock.txt",
)

load("@mypy_integration_pip_deps//:requirements.bzl", install_deps_mypy="install_deps")

install_deps_mypy()
```

**Comment by ph03** [comment]
Works great, thanks! Only additional step that was missing was adding additional dependencies of mypy, e.g.,

```
tomli==2.0.1
typing-extensions==4.4.0
mypy-extensions==0.4.3
```

to the requirements lock file (I was only using `mypy==0.981` before - unsure how they were pulled in automatically before?)

**Comment by adzenith** [comment]
We've got a couple open PRs now that are upgrading the Python rules, so I'm going to close this in favor of those:
- #61
- #82
