### ISSUE TITLE
@mypy_integration_pip_deps

### ISSUE THREAD

**Issue by SvenKratzEasel** [bazel-contrib/bazel-mypy-integration#80]
`external/mypy_integration/mypy/BUILD:3:10: no such package '@mypy_integration_pip_deps_mypy//': The repository '@mypy_integration_pip_deps_mypy' could not be resolved: Repository '@mypy_integration_pip_deps_mypy' is not defined and referenced by '@mypy_integration//mypy:mypy'`

I've correctly copied the bazel WORKSPACE snipped, but can't fix this issue when invoking Python builds.

This is my Python config

```
#### Build Rules for Python
http_archive(
    name = "rules_python",
    sha256 = "a644da969b6824cc87f8fe7b18101a8a6c57da5db39caa6566ec6109f37d2141",
    strip_prefix = "rules_python-0.20.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.20.0/rules_python-0.20.0.tar.gz",
)


load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python3_10",
    # Available versions are listed in @rules_python//python:versions.bzl.
    # We recommend using the same version your team is already standardized on.
    python_version = "3.10",
)

load("@python3_10//:defs.bzl", "interpreter")


load("@rules_python//python:pip.bzl", "install")

pip_parse(
    name = "pip",
    python_interpreter_target = interpreter,
    requirements_lock = "//third_party/python:requirements.txt",
)

load("@pip//:requirements.bzl", "install_deps")

install_deps()
####### 
```

I'm also using the aspect integration in .bazelrc:
```
build --aspects @mypy_integration//:mypy.bzl%mypy_aspect
build --output_groups=+mypy
```

**Comment by arahatashun** [comment]
@SvenKratzEasel 

https://github.com/bazel-contrib/bazel-mypy-integration/issues/69

This issue may be related to your issue.

**Comment by EricWiener** [comment]
Also seeing this issue

**Comment by kawfong** [comment]
It's because `rules_python` was updated in 0.14.0 and updated `pip_install` to `pip_parse` and `pip_parse` requires `install_deps` to actually download the dependencies. For example, 
```
# Load the starlark macro, which will define your dependencies.
load("@mypy_integration_deps//:requirements.bzl", mypy_install_deps = "install_deps")
# Call it to define repos for your requirements.
mypy_install_deps()
```

I'm able to solve it by downgrading `rules_python` to `0.13.0`. 

Alternatively, we can prob just create a PR to update the [version](https://github.com/bazel-contrib/bazel-mypy-integration/blob/main/repositories/repositories.bzl#L9-L17) of `rules_python` and update `pip_install` [here](https://github.com/bazel-contrib/bazel-mypy-integration/blob/main/repositories/py_repositories.bzl#L17-L26)

**Comment by alexeagle** [comment]
It's too difficult for this repo to provide the whole mypy toolchain. I'm closing this with a plan of instead having the mypy defined in the user's repository and just passed to the mypy rule as a label. Follow https://github.com/aspect-build/rules_lint/issues/79
